using MudBlazor;

namespace PlayBlazor.DemoHost;

/// <summary>Maps component display names to MudBlazor Material icons for the explorer.</summary>
public static class ComponentIcons
{
    private static readonly Dictionary<string, string> Map = new(StringComparer.Ordinal)
    {
        ["MudButton"] = Icons.Material.Filled.SmartButton,
        ["MudIconButton"] = Icons.Material.Filled.TouchApp,
        ["MudToggleIconButton"] = Icons.Material.Filled.TouchApp,
        ["MudFab"] = Icons.Material.Filled.Add,
        ["MudFabMenu"] = Icons.Material.Filled.Add,
        ["MudFabMenuItem"] = Icons.Material.Filled.Add,
        ["MudButtonGroup"] = Icons.Material.Filled.SmartButton,
        ["MudCheckBox"] = Icons.Material.Filled.CheckBox,
        ["MudSwitch"] = Icons.Material.Filled.ToggleOn,
        ["MudRadio"] = Icons.Material.Filled.RadioButtonChecked,
        ["MudRadioGroup"] = Icons.Material.Filled.RadioButtonChecked,
        ["MudRating"] = Icons.Material.Filled.Star,
        ["MudRatingItem"] = Icons.Material.Filled.Star,
        ["MudSelect"] = Icons.Material.Filled.List,
        ["MudSelectItem"] = Icons.Material.Filled.List,
        ["MudList"] = Icons.Material.Filled.List,
        ["MudListItem"] = Icons.Material.Filled.List,
        ["MudListSubheader"] = Icons.Material.Filled.List,
        ["MudTextField"] = Icons.Material.Filled.TextFields,
        ["MudInput"] = Icons.Material.Filled.TextFields,
        ["MudInputString"] = Icons.Material.Filled.TextFields,
        ["MudInputControl"] = Icons.Material.Filled.TextFields,
        ["MudInputLabel"] = Icons.Material.Filled.TextFields,
        ["MudRangeInput"] = Icons.Material.Filled.TextFields,
        ["MudMask"] = Icons.Material.Filled.TextFields,
        ["MudField"] = Icons.Material.Filled.TextFields,
        ["MudNumericField"] = Icons.Material.Filled.Calculate,
        ["MudSlider"] = Icons.Material.Filled.LinearScale,
        ["MudAutocomplete"] = Icons.Material.Filled.Search,
        ["MudForm"] = Icons.Material.Filled.Assignment,
        ["MudFileUpload"] = Icons.Material.Filled.CloudUpload,
        ["MudTable"] = Icons.Material.Filled.TableChart,
        ["MudSimpleTable"] = Icons.Material.Filled.TableChart,
        ["MudDataGrid"] = Icons.Material.Filled.TableChart,
        ["MudDataGridPager"] = Icons.Material.Filled.TableChart,
        ["MudTablePager"] = Icons.Material.Filled.TableChart,
        ["Bar"] = Icons.Material.Filled.BarChart,
        ["StackedBar"] = Icons.Material.Filled.BarChart,
        ["MudChart"] = Icons.Material.Filled.BarChart,
        ["Line"] = Icons.Material.Filled.ShowChart,
        ["TimeSeries"] = Icons.Material.Filled.ShowChart,
        ["ScatterPlot"] = Icons.Material.Filled.ShowChart,
        ["Pie"] = Icons.Material.Filled.PieChart,
        ["Donut"] = Icons.Material.Filled.DonutLarge,
        ["HeatMap"] = Icons.Material.Filled.GridOn,
        ["MudHeatMapCell"] = Icons.Material.Filled.GridOn,
        ["MudDatePicker"] = Icons.Material.Filled.DateRange,
        ["MudDateRangePicker"] = Icons.Material.Filled.DateRange,
        ["MudTimePicker"] = Icons.Material.Filled.Schedule,
        ["MudColorPicker"] = Icons.Material.Filled.Palette,
        ["MudImage"] = Icons.Material.Filled.Image,
        ["MudIcon"] = Icons.Material.Filled.InsertEmoticon,
        ["MudLink"] = Icons.Material.Filled.Link,
        ["MudAlert"] = Icons.Material.Filled.Announcement,
        ["MudBadge"] = Icons.Material.Filled.Badge,
        ["MudAvatar"] = Icons.Material.Filled.Person,
        ["MudAvatarGroup"] = Icons.Material.Filled.Group,
        ["MudChip"] = Icons.Material.Filled.Label,
        ["MudChipSet"] = Icons.Material.Filled.Label,
        ["MudMenu"] = Icons.Material.Filled.Menu,
        ["MudMenuItem"] = Icons.Material.Filled.Menu,
        ["MudNavMenu"] = Icons.Material.Filled.Menu,
        ["MudNavGroup"] = Icons.Material.Filled.Menu,
        ["MudNavLink"] = Icons.Material.Filled.Link,
        ["MudGrid"] = Icons.Material.Filled.GridView,
        ["MudItem"] = Icons.Material.Filled.GridView,
        ["MudCarousel"] = Icons.Material.Filled.ViewCarousel,
        ["MudCarouselItem"] = Icons.Material.Filled.ViewCarousel,
        ["MudTabs"] = Icons.Material.Filled.Tab,
        ["MudTabPanel"] = Icons.Material.Filled.Tab,
        ["MudDynamicTabs"] = Icons.Material.Filled.Tab,
        ["MudDialog"] = Icons.Material.Filled.Forum,
        ["MudMessageBox"] = Icons.Material.Filled.Forum,
        ["MudTooltip"] = Icons.Material.Filled.Info,
        ["MudProgressCircular"] = Icons.Material.Filled.Autorenew,
        ["MudProgressLinear"] = Icons.Material.Filled.LinearScale,
        ["MudStepper"] = Icons.Material.Filled.Timeline,
        ["MudStep"] = Icons.Material.Filled.Timeline,
        ["MudTimeline"] = Icons.Material.Filled.Timeline,
        ["MudTimelineItem"] = Icons.Material.Filled.Timeline,
        ["MudTreeView"] = Icons.Material.Filled.AccountTree,
        ["MudTreeViewItem"] = Icons.Material.Filled.AccountTree,
        ["MudTreeViewItemToggleButton"] = Icons.Material.Filled.AccountTree,
        ["MudExpansionPanel"] = Icons.Material.Filled.UnfoldMore,
        ["MudExpansionPanels"] = Icons.Material.Filled.UnfoldMore,
        ["MudCollapse"] = Icons.Material.Filled.UnfoldMore,
        ["MudDrawer"] = Icons.Material.Filled.MenuOpen,
        ["MudDrawerContainer"] = Icons.Material.Filled.MenuOpen,
        ["MudDrawerHeader"] = Icons.Material.Filled.MenuOpen,
        ["MudAppBar"] = Icons.Material.Filled.WebAsset,
        ["MudToolBar"] = Icons.Material.Filled.Build,
        ["MudPagination"] = Icons.Material.Filled.MoreHoriz,
        ["MudBreadcrumbs"] = Icons.Material.Filled.NavigateNext,
        ["BreadcrumbLink"] = Icons.Material.Filled.NavigateNext,
        ["BreadcrumbSeparator"] = Icons.Material.Filled.NavigateNext,
        ["MudOverlay"] = Icons.Material.Filled.Layers,
        ["MudPaper"] = Icons.Material.Filled.Layers,
        ["MudCard"] = Icons.Material.Filled.Description,
        ["MudCardActions"] = Icons.Material.Filled.Description,
        ["MudCardContent"] = Icons.Material.Filled.Description,
        ["MudCardHeader"] = Icons.Material.Filled.Description,
        ["MudCardMedia"] = Icons.Material.Filled.Description,
        ["MudScrollToTop"] = Icons.Material.Filled.ArrowUpward,
        ["MudPopover"] = Icons.Material.Filled.ChatBubble,
        ["MudHighlighter"] = Icons.Material.Filled.Brush,
        ["MudText"] = Icons.Material.Filled.TextFields,
        ["MudDivider"] = Icons.Material.Filled.Remove,
        ["MudSpacer"] = Icons.Material.Filled.Remove,
        ["MudSkeleton"] = Icons.Material.Filled.BlurOn,
        ["MudSnackbarElement"] = Icons.Material.Filled.Notifications,
        ["SnackbarMessageText"] = Icons.Material.Filled.Notifications,
        ["SnackbarMessageMarkupString"] = Icons.Material.Filled.Notifications,
        ["SnackbarMessageRenderFragment"] = Icons.Material.Filled.Notifications,
        ["MudDropContainer"] = Icons.Material.Filled.DragIndicator,
        ["MudDropZone"] = Icons.Material.Filled.DragIndicator,
        ["MudDragHandle"] = Icons.Material.Filled.DragIndicator,
        ["MudDynamicDropItem"] = Icons.Material.Filled.DragIndicator,
    };

    public static string? Resolve(Type componentType)
    {
        var name = componentType.Name;
        var backtick = name.IndexOf('`');
        if (backtick >= 0)
        {
            name = name[..backtick];
        }

        return Map.GetValueOrDefault(name, Icons.Material.Outlined.Widgets);
    }
}
