using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using MudBlazor;
using MudBlazor.Services;
using PlayBlazor;
using PlayBlazor.DemoHost;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");

builder.Services.AddMudServices();
builder.Services.AddPlayBlazor(options =>
{
    options.For<MudButton>().Slot(nameof(MudButton.ChildContent),
        b => b.AddContent(0, "Click me"));
    options.For<MudAlert>().Slot(nameof(MudAlert.ChildContent),
        b => b.AddContent(0, "Every control here was generated by reflection."));
});

await builder.Build().RunAsync();
