using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using MudBlazor;
using MudBlazor.Services;
using PlayBlazor;
using PlayBlazor.DemoHost;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");

builder.Services.AddMudServices();
builder.Services.AddPlayBlazor(options =>
{
    options.For<MudButton>().Slot(nameof(MudButton.ChildContent),
        b => b.AddContent(0, "Click me"));
    options.For<MudAlert>().Slot(nameof(MudAlert.ChildContent),
        b => b.AddContent(0, "Every control here was generated by reflection."));

    // Providers make no sense as playground specimens.
    options.Exclude<MudThemeProvider>()
        .Exclude<MudPopoverProvider>()
        .Exclude<MudDialogProvider>()
        .Exclude<MudSnackbarProvider>();

    // Demonstrates the theme hook: the host wraps every specimen and can react to the
    // environment (a real MudBlazor docs site would drive its theme provider here).
    options.ThemeWrapper = context => builder =>
    {
        builder.OpenElement(0, "div");
        builder.AddAttribute(1, "class", context.Environment.Dark ? "demo-specimen demo-specimen-dark" : "demo-specimen");
        builder.AddContent(2, context.Content);
        builder.CloseElement();
    };
});

await builder.Build().RunAsync();
