using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using MudBlazor;
using MudBlazor.Services;
using PlayBlazor;
using PlayBlazor.DemoHost;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");

builder.Services.AddMudServices();
builder.Services.AddPlayBlazor(options =>
{
    options.For<MudButton>().Slot(nameof(MudButton.ChildContent),
        b => b.AddContent(0, "Click me"));
    options.For<MudAlert>().Slot(nameof(MudAlert.ChildContent),
        b => b.AddContent(0, "Every control here was generated by reflection."));

    // Composition graph: a grid column is only meaningful inside its grid. The scaffold
    // provides the parent graph and sample data; parameter presets fill the non-drivable
    // Property expression. The played specimen stays fully driven by the generated controls.
    options.For<PropertyColumn<Person, string>>()
        .Parameter(nameof(PropertyColumn<Person, string>.Property),
            (System.Linq.Expressions.Expression<Func<Person, string>>)(p => p.Name))
        .Scaffold(specimen => builder =>
        {
            builder.OpenComponent<MudDataGrid<Person>>(0);
            builder.AddComponentParameter(1, nameof(MudDataGrid<Person>.Items), Person.Samples);
            builder.AddComponentParameter(2, nameof(MudDataGrid<Person>.Columns), (RenderFragment)(columns =>
            {
                columns.AddContent(0, specimen);
                columns.OpenComponent<PropertyColumn<Person, int>>(1);
                columns.AddComponentParameter(2, nameof(PropertyColumn<Person, int>.Property),
                    (System.Linq.Expressions.Expression<Func<Person, int>>)(p => p.Age));
                columns.CloseComponent();
            }));
            builder.CloseComponent();
        });

    // The grid itself: sample data via a parameter preset, columns via a slot preset.
    options.For<MudDataGrid<Person>>()
        .Parameter(nameof(MudDataGrid<Person>.Items), Person.Samples)
        .Slot(nameof(MudDataGrid<Person>.Columns), columns =>
        {
            columns.OpenComponent<PropertyColumn<Person, string>>(0);
            columns.AddComponentParameter(1, nameof(PropertyColumn<Person, string>.Property),
                (System.Linq.Expressions.Expression<Func<Person, string>>)(p => p.Name));
            columns.CloseComponent();
            columns.OpenComponent<PropertyColumn<Person, string>>(2);
            columns.AddComponentParameter(3, nameof(PropertyColumn<Person, string>.Property),
                (System.Linq.Expressions.Expression<Func<Person, string>>)(p => p.Role));
            columns.CloseComponent();
            columns.OpenComponent<PropertyColumn<Person, int>>(4);
            columns.AddComponentParameter(5, nameof(PropertyColumn<Person, int>.Property),
                (System.Linq.Expressions.Expression<Func<Person, int>>)(p => p.Age));
            columns.CloseComponent();
        });

    // Providers make no sense as playground specimens.
    options.Exclude<MudThemeProvider>()
        .Exclude<MudPopoverProvider>()
        .Exclude<MudDialogProvider>()
        .Exclude<MudSnackbarProvider>();

    // Demonstrates the theme hook: the host wraps every specimen and can react to the
    // environment (a real MudBlazor docs site would drive its theme provider here).
    options.ThemeWrapper = context => builder =>
    {
        builder.OpenElement(0, "div");
        builder.AddAttribute(1, "class", context.Environment.Dark ? "demo-specimen demo-specimen-dark" : "demo-specimen");
        builder.AddContent(2, context.Content);
        builder.CloseElement();
    };
});

await builder.Build().RunAsync();
